// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkbEPuzJ1qhMK-9x1EyPWPKJ6lrdOGtJ4',
    appId: '1:70812808856:web:96fbe833a1292624bac2ed',
    messagingSenderId: '70812808856',
    projectId: 'foodify-app-293fa',
    authDomain: 'foodify-app-293fa.firebaseapp.com',
    storageBucket: 'foodify-app-293fa.appspot.com',
    measurementId: 'G-D6XQW8SES6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEE7Fnohvtqx8tUkKqY6NChc0bGmOR5yU',
    appId: '1:70812808856:android:158be099fa936743bac2ed',
    messagingSenderId: '70812808856',
    projectId: 'foodify-app-293fa',
    storageBucket: 'foodify-app-293fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-JtVmPQZDs9Do0Ub0UoiuTVPggaBCHw',
    appId: '1:70812808856:ios:dea7cecdbebc1b30bac2ed',
    messagingSenderId: '70812808856',
    projectId: 'foodify-app-293fa',
    storageBucket: 'foodify-app-293fa.appspot.com',
    iosClientId: '70812808856-srkrt0fgr87p0j4tvkjpu2gfjrmvg7m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA-JtVmPQZDs9Do0Ub0UoiuTVPggaBCHw',
    appId: '1:70812808856:ios:dea7cecdbebc1b30bac2ed',
    messagingSenderId: '70812808856',
    projectId: 'foodify-app-293fa',
    storageBucket: 'foodify-app-293fa.appspot.com',
    iosClientId: '70812808856-srkrt0fgr87p0j4tvkjpu2gfjrmvg7m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComerce',
  );
}
